/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import static controlador.Control8Advertencia.eventoBtnAdvertenciaSiguiente;
import controlador.ControladorAuto;
import controlador.ImagePane;
import modelo.Auto;
import vista.VistaAuto;

/**
 *
 * @author dcrio
 */
public class Ventana8Advertencia extends javax.swing.JFrame {

    /**
     * Creates new form Ventana8Advertencia
     */
    private VistaAuto vistaAuto;
    
    public Ventana8Advertencia() {
        initComponents();
        transparenciaButton();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new ImagePane("C:\\Users\\dcrio\\Documents\\NetBeansProjects\\Cartmans_Adventure\\src\\main\\java\\imagenes\\FondoAdvertencia.png");
        btnAdvertenciaSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdvertenciaSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdvertenciaSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 427, Short.MAX_VALUE)
                .addComponent(btnAdvertenciaSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 362, Short.MAX_VALUE)
                .addComponent(btnAdvertenciaSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdvertenciaSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdvertenciaSiguienteActionPerformed
        // TODO add your handling code here:
        eventoBtnAdvertenciaSiguiente();
    }//GEN-LAST:event_btnAdvertenciaSiguienteActionPerformed

    public void transparenciaButton(){
        btnAdvertenciaSiguiente.setOpaque(false);
        btnAdvertenciaSiguiente.setContentAreaFilled(false);
        btnAdvertenciaSiguiente.setBorderPainted(false);
    }
    
    /**
     * @param args the command line arguments
     */
    
    
    public void setVistaAuto(VistaAuto vistaAuto) {
        this.vistaAuto = vistaAuto;
    }

    public VistaAuto getVistaAuto() {
        return vistaAuto;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdvertenciaSiguiente;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
